version: "3.7"

services:
  db:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    container_name: "mysql-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: users123
    volumes:
        - ./init.sql:/data/application/init.sql
